// placeholder data while we wait to set the database up
import { Project, Task } from "./definitions";
export const placeholderProjects: Project[] = [
    {
        id: '1',
        name: 'Project 1',
        description: 'Description 1',
        start_date: '2025-01-01',
        completed_date: null,
        completed: false,
        priority: 1,
        tags: ['tag1', 'tag2'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
    },
    {
        id: '2',
        name: 'Project 2',
        description: 'Description 2',
        start_date: '2024-01-01',
        completed_date: '2025-01-01',
        completed: true,
        priority: 2,
        tags: ['tag1'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
    },
    {
        id: '3',
        name: 'Project 3',
        description: 'Description 3',
        start_date: '2025-01-01',
        completed_date: null,
        completed: false,
        priority: 1,
        tags: ['tag5'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
    },
];
export const placeholderTasks: Task[] = [
    {
        id: '1',
        name: 'Task 1',
        description: 'Description 1',
        start_date: '2025-01-01',
        completed_date: null,
        completed: false,
        priority: 1,
        tags: ['tag3'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
        project_id: '1',
    },
    {
        id: '2',
        name: 'Task 2',
        description: 'Description 2',
        start_date: '2024-01-01',
        completed_date: '2025-01-01',
        completed: true,
        priority: 2,
        tags: ['tag1', 'tag4'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
        project_id: '2',
    },
    {
        id: '3',
        name: 'Task 3',
        description: 'Description 3',
        start_date: '2025-01-01',
        completed_date: null,
        completed: false,
        priority: 1,
        tags: ['tag5'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
        project_id: '1',
    },
    {
        id: '4',
        name: 'Task 4',
        description: 'Description 4',
        start_date: '2025-01-01',
        completed_date: null,
        completed: false,
        priority: 2,
        tags: ['tag6'],
        created_at: '2025-01-01',
        updated_at: '2025-01-01',
        project_id: '2',
    },
];
